#!/bin/bash
cat > .env <<EOF
NODE_ENV=production

# DATABASE
DATABASE_HOST=$DATABASE_HOST
DATABASE_SRV=$DATABASE_SRV
# DATABASE_PORT
DATABASE_NAME=$DATABASE_NAME
DATABASE_USERNAME=$DATABASE_USERNAME
DATABASE_PASSWORD=$DATABASE_PASSWORD
DATABASE_SSL=$DATABASE_SSL

# AWS configuration.
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET
AWS_REGION=$AWS_REGION
AWS_BUCKET_NAME=$AWS_BUCKET_NAME

# Cors Allow Origins
CORS_ORIGIN=$CORS_ORIGIN
EOF
