# This file provides instruction for Codedeploy Agent perform deployment on its EC2 instance.

version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: .aws/codedeploy-scripts/app-stop.sh
      timeout: 10
      runas: ec2-user

  BeforeInstall:
    - location: .aws/codedeploy-scripts/cleanup.sh
      timeout: 10
      runas: ec2-user

  Install:
    - location: .aws/codedeploy-scripts/install-dependencies.sh
      timeout: 1200
      runas: ec2-user

  AfterInstall:
    - location: .aws/codedeploy-scripts/build.sh
      timeout: 1200
      runas: ec2-user

  ApplicationStart:
    - location: .aws/codedeploy-scripts/app-start.sh
      timeout: 1200
      runas: ec2-user

  ValidateService:
    - location: .aws/codedeploy-scripts/app-validate.sh
      timeout: 120
      runas: ec2-user
