version: '3.3'
services:
  # backend:
  #   build:
  #     context: .
  #   container_name: nodejs
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - 3002:3002
  #   depends_on:
  #     - mysql_db

  mysql_db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'onspread_shop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'onspread'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234abcd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - '8083:80'
    environment:
      PMA_HOST: 'mysql_db'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
# Names our volume
volumes:
  my-db:
